// Todo actions
export const UPDATE_STATUS_FILTER = 'UPDATE_STATUS_FILTER'
export const RESET_TODOS = 'RESET_TODOS'

export const CREATE_TODO_REQUEST = 'CREATE_TODO_REQUEST'
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS'
export const CREATE_TODO_FAILURE = 'CREATE_TODO_FAILURE'

export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST'
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS'
export const UPDATE_TODO_FAILURE = 'UPDATE_TODO_FAILURE'

export const FETCH_TODOS_REQUEST = 'FETCH_TODOS_REQUEST'
export const FETCH_TODOS_SUCCESS = 'FETCH_TODOS_SUCCESS'
export const FETCH_TODOS_FAILURE = 'FETCH_TODOS_FAILURE'

export const FETCH_TODOS_BY_USERID_REQUEST = 'FETCH_TODOS_BY_USERID_REQUEST'
export const FETCH_TODOS_BY_USERID_SUCCESS = 'FETCH_TODOS_BY_USERID_SUCCESS'
export const FETCH_TODOS_BY_USERID_FAILURE = 'FETCH_TODOS_BY_USERID_FAILURE'

export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS'
export const DELETE_TODO_REQUEST = 'DELETE_TODO_REQUEST'
export const DELETE_TODO_FAILURE = 'DELETE_TODO_FAILURE'

export const CHANGE_TODO_STATUS_REQUEST = 'CHANGE_TODO_STATUS_REQUEST'
export const CHANGE_TODO_STATUS_FAILURE = 'CHANGE_TODO_STATUS_FAILURE'
export const CHANGE_TODO_STATUS_SUCCESS = 'CHANGE_TODO_STATUS_SUCCESS'

// User actions
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST'
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export const UPDATE_USER_FILTER = 'UPDATE_USER_FILTER'
export const TOGGLE_USER_FORM_OPEN = 'TOGGLE_USER_FORM_OPEN'
